version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: test_db_password
    volumes:
      - backend-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    volumes:
      - backend-redis:/var/lib/redis/data
  backend:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./backend:/opt/app
    depends_on: 
      - postgres
    env_file:
      - .env
  frontend:
    image: "node:16-alpine"
    user: "node"
    working_dir: /opt/app/frontend
    volumes:
      - ./frontend:/opt/app/frontend
    command: "yarn start"
    depends_on:
      - backend
    env_file:
      - .env
  nginx: 
    image: "nginx:1.21.4-alpine"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - "$APP_PORT:80"
    env_file: 
      - .env
    
      
volumes:
  backend-postgres:
  backend-redis:
