version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: url-shortener-be
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - "$PG_PORT:5432"
    volumes:
      - url-shortener-be-postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - url-shortener-be-redis:/var/lib/redis/data
  url-shortener-be:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - ./url-shortener-be:/opt/app
    links:
      - postgres
      - redis
    ports:
      - "$RAILS_PORT:3000"
    env_file:
      - .env
  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env
  frontend:
    image: "node:16-alpine"
    user: "node"
    working_dir: /opt/app/frontend
    volumes:
      - ./frontend:/opt/app/frontend
    command: "yarn start"
    depends_on:
      - url-shortener-be
    ports:
      - "$REACT_PORT:3000"
    env_file:
      - .env
volumes:
  url-shortener-be-postgres:
  url-shortener-be-redis:
